steps:
  build-debian-bookworm-gcc:
    group: compile
    image: debian:bookworm-slim
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-debian-minimal-deps.sh
      - CC=gcc make
      - sha256sum *.so
  build-debian-bookworm-clang:
    group: compile
    image: debian:bookworm-slim
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-debian-minimal-deps.sh
      - CC=clang make
      - sha256sum *.so
  build-debian-sid-cross:
    group: compile
    image: debian:sid-slim
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-debian-sid-cross-deps.sh
      - ./misc/test-c-lib-cross.sh
  build-debian-bookworm-python:
    group: compile
    image: debian:bookworm
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-debian-deps.sh
      - make -f Makefile.packages packages
      - dpkg -i dist/python3-highctidh_*.deb
      - pytest-3 -v -n`nproc` --doctest-modules
      - sha256sum dist/*.deb
      - ls -alh dist/*.deb
      - sha256sum dist/*.whl
      - ls -alh dist/*.whl
  build-alpine-3.18-gcc:
    group: compile
    image: alpine:3.18
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-arch-deps.sh
      - CC=gcc make -f Makefile.packages wheel
      - CC=gcc make
      - ls -alh dist/*.whl
      - sha256sum dist/*.whl
      - sha256sum *.so
  build-alpine-3.18-clang:
    group: compile
    image: alpine:3.18
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-arch-deps.sh
      - CC=clang make -f Makefile.packages wheel
      - CC=clang make
      - ls -alh dist/*.whl
      - sha256sum dist/*.whl
      - sha256sum *.so
  build-alpine-3.19-gcc:
    group: compile
    image: alpine:3.19
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-arch-deps.sh
      - CC=gcc make -f Makefile.packages wheel
      - CC=gcc make
      - ls -alh dist/*.whl
      - sha256sum dist/*.whl
      - sha256sum *.so
  build-alpine-3.19-clang:
    group: compile
    image: alpine:3.19
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-arch-deps.sh
      - CC=clang make -f Makefile.packages wheel
      - CC=clang make
      - ls -alh dist/*.whl
      - sha256sum dist/*.whl
      - sha256sum *.so
  build-debian-bookworm-golang:
    group: compile
    image: debian:bookworm-slim
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - export WORKDIR=`pwd`
      - ./misc/install-debian-go-deps.sh
      - make -f Makefile.packages go-test-cross
