name: Alpine multi-arch docker 64bit golang test (clang)
on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  alpine-multiarch-64bit-qemu-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang", "gcc"]
        DOCKER_ARCH_ARGS: ["--platform linux/arm64/v8 arm64v8/alpine:3.18",
                           "--platform linux/amd64 amd64/alpine:3.18"] #,
        #                  "--platform linux/riscv64 riscv64/alpine:edge",
        #                  "--platform linux/ppc64le ppc64le/alpine:3.18",
        #                  "--platform linux/s390x s390x/alpine:3.18"]
      fa#l-fast: false
    steps:
      #      - name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y docker qemu-user-static

      - name: check kernel
        run: |
          mount | grep binfmt_misc
          docker info
          uname -a

      - name: Setup qemu user static
        continue-on-error: false
        run: |
          docker pull multiarch/qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Run Golang tests in Docker under qemu
        continue-on-error: false
        run: |
          docker run \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e "CC=${{ matrix.CC }}" \
            -e "CFLAGS=-fno-lto" \
            --rm \
            ${{ matrix.DOCKER_ARCH_ARGS}} \
            /bin/sh -c "./misc/test-golang-alpine-docker-qemu.sh"
