name: Debian multi-arch docker 64bit golang test (clang)
on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  debian-multiarch-64bit-qemu-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang"]
        DOCKER_ARCH_ARGS: ["--platform linux/arm64/v8 arm64v8/debian",
                           "--platform linux/amd64 amd64/debian"] #,
           #               "--platform linux/riscv64 riscv64/debian",
           #               "--platform linux/ppc64le ppc64le/debian",
           #               "--platform linux/s390x s390x/debian"]
      fail-fast: false
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt install -y --no-install-recommends docker

      - name: check kernel
        run: |
          mount | grep binfmt_misc
          docker info
          uname -a

      - name: Run Golang tests in Docker under qemu
        continue-on-error: true
        run: |
          docker run \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e "CC=${{ matrix.CC }}" \
            --rm \
            ${{ matrix.DOCKER_ARCH_ARGS}} \
            /bin/sh -c "./misc/debian-multi-arch-docker-qemu-golang-test.sh"
