name: Alpine multi-arch docker build and test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker-multiarch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang"]
        PORTABLE: ["1"]
        CONTAINER: ["alpine"]
        DOCKER_ARCH_ARGS: ["--platform linux/arm64/v8 arm64v8/alpine",
                      "--platform linux/amd64 amd64/alpine",
                      "--platform linux/arm32/v6 arm32v6/alpine",
                      "--platform linux/arm32/v7 arm32v7/alpine",
                      "--platform linux/i386 i386/alpine",
                      "--platform linux/riscv64 riscv64/alpine",
                      "--platform linux/ppc64le ppc64le/alpine",
                      "--platform linux/s390x s390x/alpine"]
      fail-fast: false
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - uses: actions/checkout@v4

    - name: Install requirements
      run : |
        apt install -y --no-recommends docker

    - name: check kernel
      run: |
        mount | grep binfmt_misc
        docker info
        uname -a

     - name: Run in Docker
        run: |
          docker run \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e "CC=${{ matrix.CC }}" \
            -e "HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }}" \
            -e "CFLAGS=-fno-lto" \
            --rm -it \
            ${{ matrix.DOCKER_ARCH_ARGS}} \
            /bin/bash \
            -c "cd /highctidh && ./misc/install-alpine-deps.sh && make alpine-multi-arch"
