name: Alpine multi-arch docker build and test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: ["clang"]
        PORTABLE: ["1"]
        CONTAINER: ["alpine"]
        ARCH: ["amd64", "arm32v6", "arm32v7", "i386", "arm64v8", "ppc64le",
               "riscv64", "s390x"]
      fail-fast: false
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

    - uses: actions/checkout@v4

    - name: Install requirements
      run : |
        apt install -y --no-recommends docker

    - name: check kernel
      run: |
        mount | grep binfmt_misc
        docker info
        uname -a

     - name: Run in Docker
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e "ARCH=${{ matrix.ARCH }}" \
            -e "CC=${{ matrix.CC }}" \
            -e "HIGHCTIDH_PORTABLE=${{ matrix.PORTABLE }}" \
            -e "CFLAGS=-fno-lto" \
            --platform ${{ matrix.ARCH }} \
            ${{ matrix.ARCH }}/${{ matrix.CONTAINER }} \
            ./misc/install-alpine-deps.sh && \
            make alpine-multi-arch
