name: MacOS fiat build with clang

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        OS: ["macos-11", "macos-12", "macos-13", "macos-latest"]
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install tools
      run: brew install make

    - name: Gather kernel environment
      run: uname -a

    - name: Gather toolchain info
      run: |
        clang -v
        make -v

    - name: compile
      run: HIGHCTIDH_PORTABLE=1 CC=clang MAKE=gmake gmake

#    - name: test-quick
#run: HIGHCTIDH_PORTABLE=1 CC=clang MAKE=gmake gmake test-quick
