name: Omnios fiat build with clang

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Omnios clang build of fiat backend
    env:
      LANG: "C"
      LD: "/usr/bin/ld"
      CC: "clang"
      MAKE: "gmake"
      HIGHCTIDH_PORTABLE: "1"
    steps:
    - uses: actions/checkout@v4
    - name: Test in Omnios
      id: test
      uses: vmactions/omnios-vm@v1
      with:
        release: "r151046"
        envs: 'LANG LD CC MAKE HIGHCTIDH_PORTABLE'
        usesh: true
        prepare: |
          uname -a
          psrinfo -vp
          cat /etc/release
          pkg install developer/build/gnu-make
          pkg install ooce/developer/clang-18
          pkg install gcc-dev
          clang -v
          gcc -v
          gmake -v

        run: |
          HIGHCTIDH_PORTABLE=1 gmake
          HIGHCTIDH_PORTABLE=1 gmake test-quick
