name: Test Solaris build with gcc

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Solaris gcc build
    env:
      LANG: "C"
      LD: "/usr/bin/ld"
      CC: "gcc"
      MAKE: "/usr/bin/gmake"
      HIGHCTIDH_PORTABLE: "0"
    steps:
    - uses: actions/checkout@v4
    - name: Test in Solaris
      id: test
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-gcc"
        envs: 'LD CC MAKE HIGHCTIDH_PORTABLE'
        usesh: true
        prepare: |
          uname -a
          isainfo -v
          pkgutil -U
          pkgutil -y -i gmake

        run: |
          gmake
          gmake test-quick
