name: Windows Golang build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        #OS: ["windows-2019", "windows-2022"]
        OS: ["windows-2022"]
        go-version: ["1.22.x"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        shell: bash
        run: go version

      - name: Downgrade mingw due to cgo
        shell: bash
        run: |
          choco install -y make
          choco install -y mingw --version 10.2.0 --allow-downgrade

      - name: Install golang dependencies
        shell: bash
        run: |
          export HIGHCTIDH_PORTABLE=1
          export CGO_ENABLED=1
          export CGO_LDFLAGS="-DCGONUTS"
          export CC=x86_64-w64-mingw32-gcc.exe
          go get -v ./src/ctidh511
          go get -v ./src/ctidh512
          go get -v ./src/ctidh1024
          go get -v ./src/ctidh2048

      - name: Build golang
        shell: bash
        run: |
          export HIGHCTIDH_PORTABLE=1
          export CGO_ENABLED=1
          export CGO_CFLAGS="-DHIGHCTIDH_PORTABLE=1 -DCGONUTS -D__Windows__"
          export CC=x86_64-w64-mingw32-gcc.exe
          go build -x -v ./...

      - name: Golang test
        shell: bash
        run: |
          export HIGHCTIDH_PORTABLE=1
          export CGO_ENABLED=1
          export CGO_CFLAGS="-DHIGHCTIDH_PORTABLE=1 -DCGONUTS -D__Windows__"
          export CC=x86_64-w64-mingw32-gcc.exe
          go clean -x -cache
          go test -x -v ./...

