name: Windows and MacOS Python clang build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: ["windows-2022", "macos-latest"]
        CC: ["clang"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        exclude:
          - OS: "windows-2022"
            python-version: "3.9"
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Gather runtime environment
      shell: bash
      run: |
       python -V 
       bash --version

    - name: Install dependencies
      shell: bash
      run: python -m pip install --upgrade build pip setuptools wheel pytest pytest-xdist

    - name: Build wheel
      shell: bash
      run: |
        export HIGHCTIDH_PORTABLE=1
        export WINDOWS=1
        export CC=${{ matrix.CC }} MAKE=make
        cd src && python -m build
        pip install --force-reinstall dist/highctidh-*.whl

    - name: Test with pytest
      shell: bash
      run: |
        python -c 'from highctidh import bench; bench.simple_bench()'
        pytest -v
