name: Windows Golang clang build and test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        #OS: ["windows-2019", "windows-2022"]
        OS: ["windows-2022"]
        CC: ["clang"]
        #go-version: [ "1.20", "1.21.x", "1.22.x"]
        go-version: ["1.22.2"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        shell: bash
        run: go version

      - name: Install golang dependencies
        shell: bash
        run: |
          export HIGHCTIDH_PORTABLE=1
          export CC=${{ matrix.CC }}
          export CGO_ENABLED=1
          export CGO_LDFLAGS="-ladvapi32.lib"
          export CGO_CFLAGS="-DHIGHCTIDH_PORTABLE=1 -DCGONUTS -D__Windows__"
          go get -v ./src/ctidh511
          go get -v ./src/ctidh512
          go get -v ./src/ctidh1024
          go get -v ./src/ctidh2048

      - name: Build golang
        shell: bash
        run: |
          export HIGHCTIDH_PORTABLE=1
          export CC=${{ matrix.CC }}
          export CGO_ENABLED=1
          export CGO_LDFLAGS="-ladvapi32.lib"
          export CGO_CFLAGS="-DHIGHCTIDH_PORTABLE=1 -DCGONUTS -D__Windows__"
          go build -x -v ./...

      - name: Golang test
        shell: bash
        run: |
          export HIGHCTIDH_PORTABLE=1
          export CC=${{ matrix.CC }}
          export CGO_ENABLED=1
          export CGO_LDFLAGS="-ladvapi32.lib -Wl,--no-as-needed"
          export CGO_CFLAGS="-DHIGHCTIDH_PORTABLE=1 -DCGONUTS -D__Windows__"
          go test -x -v ./...

